package com.sapphire.demo.mapper;

import com.sapphire.demo.model.LikeRecord;
import com.sapphire.demo.model.LikeRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface LikeRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likeRecord
     *
     * @mbg.generated
     */
    long countByExample(LikeRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likeRecord
     *
     * @mbg.generated
     */
    int deleteByExample(LikeRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likeRecord
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likeRecord
     *
     * @mbg.generated
     */
    int insert(LikeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likeRecord
     *
     * @mbg.generated
     */
    int insertSelective(LikeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likeRecord
     *
     * @mbg.generated
     */
    List<LikeRecord> selectByExampleWithRowbounds(LikeRecordExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likeRecord
     *
     * @mbg.generated
     */
    List<LikeRecord> selectByExample(LikeRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likeRecord
     *
     * @mbg.generated
     */
    LikeRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likeRecord
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LikeRecord record, @Param("example") LikeRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likeRecord
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LikeRecord record, @Param("example") LikeRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likeRecord
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LikeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likeRecord
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LikeRecord record);
}