package com.sapphire.demo.mapper;

import com.sapphire.demo.model.ViewRecord;
import com.sapphire.demo.model.ViewRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ViewRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table viewRecord
     *
     * @mbg.generated
     */
    long countByExample(ViewRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table viewRecord
     *
     * @mbg.generated
     */
    int deleteByExample(ViewRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table viewRecord
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table viewRecord
     *
     * @mbg.generated
     */
    int insert(ViewRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table viewRecord
     *
     * @mbg.generated
     */
    int insertSelective(ViewRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table viewRecord
     *
     * @mbg.generated
     */
    List<ViewRecord> selectByExampleWithRowbounds(ViewRecordExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table viewRecord
     *
     * @mbg.generated
     */
    List<ViewRecord> selectByExample(ViewRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table viewRecord
     *
     * @mbg.generated
     */
    ViewRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table viewRecord
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ViewRecord record, @Param("example") ViewRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table viewRecord
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ViewRecord record, @Param("example") ViewRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table viewRecord
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ViewRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table viewRecord
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ViewRecord record);
}